### ISSUE TITLE
Modify optimization loop to not be solely load-based

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#123]
The current implementation below does not drive the optimization of communication weights:

<img width="568" alt="Screen Shot 2021-12-09 at 1 43 10 PM" src="https://user-images.githubusercontent.com/17439260/145398577-aadb8ff1-d970-4109-9368-0c452a5a7748.png">

**Comment by ppebay** [comment]
Results with 
```
criterion:
<img width="367" alt="Screen Shot 2021-12-13 at 4 33 33 PM" src="https://user-images.githubusercontent.com/17439260/145841352-21003085-4cc4-4cfa-9abc-36f37a84f878.png">
<img width="368" alt="Screen Shot 2021-12-13 at 4 33 40 PM" src="https://user-images.githubusercontent.com/17439260/145841374-5c3bcf46-e019-483e-9344-6c5e0650086b.png">
<img width="403" alt="Screen Shot 2021-12-13 at 4 35 51 PM" src="https://user-images.githubusercontent.com/17439260/145841396-28550511-2420-4481-88dc-c49651b0e794.png">

  name: "LowerTotalWork"
  parameters:
    alpha: 0.
    beta: 1000000.
    actual_dst_load: False
n_iterations: 8
n_rounds: 4
fanout: 4
```
As expected total communication weight monotonically decreases (while **no** optimization for load takes place -- also expected with parameters above):
```
[Statistics] Descriptive statistics of final rank loads:
	cardinality: 4  sum: 8  imbalance: 1.25
	minimum: 0  mean: 2  maximum: 4.5
	standard deviation: 1.62019  variance: 2.625
	skewness: 0.440867  kurtosis excess: -1
[Statistics] Descriptive statistics of final link weights:
	cardinality: 1  sum: 0.5  imbalance: 0
	minimum: 0.5  mean: 0.5  maximum: 0.5
	standard deviation: 0  variance: 0
	skewness: nan  kurtosis excess: nan
```
**HOWEVER**, it is theoretically possible to achieve **0** total communication weight by moving all objects on same rank. Why this does not occur warrants further study.
