### ISSUE TITLE
Describe conditions for the new LBAF test

### ISSUE THREAD

**Issue by marcinwrobel1986** [DARMA-tasking/LB-analysis-framework#125]
### TODO:
- because current CI test does not make any sense there is a need to describe a condition which could be implemented in a CI test and would make sense
- maybe a new condition could be a ratio between theoretical imbalance value and the one achieved after load balancing

**Comment by ppebay** [comment]
One test case:
```
work_model:
  name: "AffineCombination"
  parameters:
    alpha: 1.
    beta: 0.
    gamma: 0.
criterion:
  name: "Tempered"
  parameters:
    actual_destination_load: True
deterministic_transfer: True
n_iterations: 8
n_rounds: 4
fanout: 4
phase_id: 0
log_file: "data/synthetic_lb_stats/stats"
file_suffix: json
exodus: True
x_procs: 2
y_procs: 2
z_procs: 1
output_dir: "output"
order_strategy: arbitrary
logging_level: debug
```

And for this one, we need to verify that we find 
```
[lbsStatistics] Descriptive statistics of final rank loads:
[lbsStatistics] 	cardinality: 4  sum: 8  imbalance: 0
```
specifically we need to verify the value of `imbalance` (has to be zero, so say less than 0.000001).
