### ISSUE TITLE
Accept range in phase indices in lbaf config

### ISSUE THREAD

**Issue by nmm0** [DARMA-tasking/LB-analysis-framework#277]
e.g. if we want to simulate 100 phases we would want to be able to have something like:

```yml
from_data:
  phase_ids:
    - [0,100]
```

@ppebay mentioned I should file an issue for this

**Comment by marcinwrobel1986** [comment]
@nmm0 sure, that make sense. I will try to do that before the LB meeting.

**Comment by marcinwrobel1986** [comment]
Ok, so the possibilities will be:
```yaml
# Specify input
from_data:
  data_stem: "../data/nolb-8color-16nodes-11firstphases/data"
  phase_ids:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
```
```yaml
# Specify input
from_data:
  data_stem: "../data/nolb-8color-16nodes-11firstphases/data"
  phase_ids: [1, 2, 3, 4, 5, 6]
```
Two examples above present current capabilities.

Below implemented range (phase_ids must be a string):
```yaml
# Specify input
from_data:
  data_stem: "../data/nolb-8color-16nodes-11firstphases/data"
  phase_ids: "1-6"
```
Three examples above are representing the same.
