### ISSUE TITLE
Make categorical labels integer when numeric

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#370]
In cases where the QOI is categorical, make categories integers (i.e., not print the decimal part) so that they fit better

As suggested by @nlslatt

**Comment by ppebay** [comment]
Re-assigning to @cwschilly

**Comment by cwschilly** [comment]
@ppebay Could you please provide some more clarification on this issue? What is a categorical QOI?

**Comment by ppebay** [comment]
Sorry :)

_QOI:_ Quantity of Interest. This means a variable that is either directly present in the data (primary QOI) or that is derived from the data (secondary QOI). Examples: `load` is a primary QOI and `work` is a secondary QOI as is calculated from `load` and possibly communications and memory values.

_categorical:_ non-continuous data that is typically grouped in "quanta" or groups, buckets, etc. This may also result from rasterizing continuous data.

What the visualizer will do is determine whether the QOI to be displayed takes on less than 20 different values (the _support_ of the distribution); if the answer is **YES**, then it will be treated as categorical (one different color per category); if **NO**, then the color mapping will be made (pseudo-)continuous, except if the parameter `force_continuous_object_qoi` has been´ set to `true` in the configuration file (as in, e.g., `config/conf.yaml`).

I hope this clarifies; let me know otherwise.

**Comment by ppebay** [comment]
Here's an example @cwschilly :

![Screen Shot 2023-06-14 at 3 52 21 PM](https://github.com/DARMA-tasking/LB-analysis-framework/assets/17439260/5f9057f0-bdf9-4c16-9b27-383dc88d01e0)

with the following configuration file (modified `user-defined-memory-toy-problem`:
```
# Specify input
from_data:
  data_stem: ../data/user-defined-memory-toy-problem/toy_mem
  phase_ids:
    - 0
check_schema: False

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 1.0
    beta: 0.0
    gamma: 0.0
    upper_bounds:
      max_memory_usage: 8000000000.0

# Specify algorithm
algorithm:
  name: InformAndTransfer
  phase_id: 0
  parameters:
    n_iterations: 4
    n_rounds: 2
    fanout: 2
    order_strategy: arbitrary
    transfer_strategy: Clustering
    criterion: Tempered
    max_objects_per_transfer: 32
    deterministic_transfer: False

# Specify output
output_dir: ../output
output_file_stem: output_file
LBAF_Viz:
  x_ranks: 2
  y_ranks: 2
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: load
  object_qoi: shared_block_id
  save_meshes: True
  #force_continuous_object_qoi: True
write_JSON:
  compressed: True
  suffix: json
  communications: True
  offline_LB_compatible: True
```
