### ISSUE TITLE
Call VT-TV task visualizer with Python binding

### ISSUE THREAD

**Issue by pierrepebay** [DARMA-tasking/LB-analysis-framework#410]
This is to work on https://github.com/DARMA-tasking/vt-tv/issues/16 and have the link between both projects.

**Comment by ppebay** [comment]
Parameters currently read in by LBAF at startup time, such as:
```
LBAF_Viz:
  x_ranks: 2
  y_ranks: 2
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: work
  object_qoi: load
  save_meshes: True
  force_continuous_object_qoi: True
```
and subsequently passed to the `lbsVisualizer` via the class constructor and the `generate()` method, will have to be passed through vt-tv's API instead.
