### ISSUE TITLE
Identify and deprecate parts of LBAF CI/CD that are relevant to LBAF-Viz

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#503]
The goal of this issue is to identify those parts of the CI/CD (probably mostly in the configuration validator) that are relevant to the visualization component, in order to:
1. know what will have to be removed from the CI/CD once LBAF-Viz is deprecated;
2. hopefully be able to re-use some or all of those identified parts in vt-tv.

**Comment by ppebay** [comment]
In keeping with #507 the CI/CD of LBAF-Viz must be deprecated as well

**Comment by cwschilly** [comment]
### 1. Identify what will be removed for LBAF CI/CD
- Many of the config files (in `config/` and `tests/unit/config/` include `visualization` parameters.

For example:
```
# Specify output
output_dir: ../../output
output_file_stem: output_file
visualization:
  x_ranks: 2
  y_ranks: 2
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: None
  object_qoi: None
  force_continuous_object_qoi: true
  output_visualization_dir: ../../output
  output_visualization_file_stem: output_file
```

- Not part of LBAF CI/CD, but the lbsConfigurationValidator.py will need to be updated as well:
```python
Optional("visualization"): {
                "x_ranks": And(
                    int, lambda x: x > 0,
                    error="Should be of type 'int' and > 0"),
                "y_ranks": And(
                    int, lambda x: x > 0,
                    error="Should be of type 'int' and > 0"),
                "z_ranks": And(
                    int, lambda x: x > 0,
                    error="Should be of type 'int' and > 0"),
                "object_jitter": And(
                    float, lambda x: abs(x) < 1.0,
                    error="Should be of type 'float' and magnitude < 1"),
                "rank_qoi": str,
                "output_visualization_dir": str,
                "output_visualization_file_stem": str,
                Optional("object_qoi"): str,
                Optional("force_continuous_object_qoi"): bool,
                Optional("save_meshes"): bool},
```

### 2. Parts of LBAF CI that can be re-used with vt-tv

There is no explicit testing of LBAF viz

vt-tv can potentially draw from `test_lbs_vt_data_reader.py` (at least for logic for testing reading in JSON)

can also test config files with similar logic to `test_configuration_validator.py`
